// packages/devgon.io-react/src/components/Menu/index.tsx
import styled from 'styled-components';
import { Link } from 'react-router-dom';

const Navigation = styled.nav``;
const NavItem = styled.li`
    display: inline-block;
    margin: 0 10px;

    a {
        color: #000;
        text-decoration: none;
    }
`;

const Menu = () => {
    return (
        <Navigation>
            <NavItem>
                <Link to="/">Home</Link>
            </NavItem>
            <NavItem>
                <Link to="/resume">Resume</Link>
            </NavItem>
            <NavItem>
                <Link to="/contact">Contact</Link>
            </NavItem>
            <NavItem className="float-right">
                <a href="https://github.com/gonhongcheon" target="_blank" rel="noreferrer">
                    Github
                </a>
            </NavItem>
        </Navigation>
    );
};

export default Menu;

// packages/devgon.io-vue/src/components/Menu/Menu.vue
<template>
    <nav>
        <li>
            <router-link to="/">Home</router-link>
        </li>
        <li>
            <router-link to="/resume">Resume</router-link>
        </li>
        <li>
            <router-link to="/contact">Contact</router-link>
        </li>
        <li className="float-right">
            <a href="https://github.com/gonhongcheon" target="_blank" rel="noreferrer">Github</a>
        </li>
    </nav>
</template>

<script lang="ts">
export default {
    name: 'MenuComponent',
};
</script>

<style lang="scss" scoped>
li {
    display: inline-block;
    margin: 0 10px;

    a {
        color: #000;
        text-decoration: none;
    }
}
</style>
